### ISSUE TITLE
Do not remove `.git` directories by default

### ISSUE THREAD

**Issue by chipironcin** [bitnami/node-tarball-utils#4]
Currently, we are removing `.git` directories when uncompressing a tarball (see https://github.com/bitnami/node-tarball-utils/blob/master/index.js#L17). This causes unexpected behavior (i.e. https://github.com/bitnami/bitnami-docker-phabricator/issues/14).

I suggest modifying that behavior by default, but keeping the option.

**Comment by andresmgot** [comment]
The change has being made in v3.0.0:
https://github.com/bitnami/node-tarball-utils/releases/tag/v3.0.0
Thanks for reporting
